# Generated by Django 3.2 on 2023-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_registration', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hospital_ward', models.CharField(max_length=10)),
                ('room', models.PositiveIntegerField()),
                ('patient_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('admitting_department', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=100)),
                ('admitting_physician', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Información del Paciente',
                'verbose_name_plural': 'Información de los Pacientes',
            },
        ),
    ]
