# Generated by Django 3.2 on 2023-09-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_patientinformationsp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientinformation',
            options={'verbose_name': 'Patient Information', 'verbose_name_plural': 'Patients Information'},
        ),
    ]
